"""KKT-residual baseline returns a near-zero residual on noiseless data.

The baseline solves a convex QP whose objective is the squared norm of the
stationarity residuals at the *observed* (g, p).  On a noiseless dataset
generated by the same forward QP it should drive the residual very close
to zero (limited only by solver tolerance).
"""

from __future__ import annotations

import numpy as np
import pytest
import torch

from inverse_opf.baselines_kkt import kkt_residual_inverse
from inverse_opf.dc_opf import DCOpfLayer, DCOpfProblemData
from inverse_opf.graph import random_connected_incidence
from inverse_opf.seeding import set_global_seed


@pytest.mark.parametrize("seed", [0, 1])
def test_kkt_residual_small_on_noiseless(seed):
    set_global_seed(seed)
    rng = np.random.default_rng(seed)
    n, m = 4, 5
    A = random_connected_incidence(n, m, rng)

    f = rng.uniform(10.0, 40.0, size=n)
    gmax = rng.uniform(40.0, 60.0, size=n)
    pmax = rng.uniform(40.0, 60.0, size=m)
    data = DCOpfProblemData(incidence=A)
    layer = DCOpfLayer(data, eps=0.1, tau=0.01)

    T = 20
    d_np = rng.uniform(5.0, 15.0, size=(T, n))
    d = torch.tensor(d_np, dtype=torch.float32)
    f_b = torch.tensor(f, dtype=torch.float32).unsqueeze(0).repeat(T, 1)
    gmax_b = torch.tensor(gmax, dtype=torch.float32).unsqueeze(0).repeat(T, 1)
    pmax_b = torch.tensor(pmax, dtype=torch.float32).unsqueeze(0).repeat(T, 1)
    with torch.no_grad():
        g_star, _ = layer.solve(d, f_b, gmax_b, pmax_b)

    res = kkt_residual_inverse(
        data, d, g_star,
        tau=0.01, eps=0.1,
        learn_capacities=False,
        activity_tol=5e-2,
    )

    # Per-residual-entry norm. Total residual is over T*n + T*m terms.
    total_entries = T * n + T * m
    per_entry = res.residual_norm / np.sqrt(total_entries)
    assert per_entry < 5e-2, f"per-entry residual {per_entry:.3e}"
    # Recovered f should at least correlate strongly with truth on this
    # well-conditioned synthetic problem.
    assert np.isfinite(res.f).all()
    cos = float(np.dot(res.f, f) / (np.linalg.norm(res.f) * np.linalg.norm(f) + 1e-12))
    assert cos > 0.5, f"cos(f_kkt, f_true) = {cos:.3f}"
